// Generated by CoffeeScript 1.8.0
var fs, list, modules, numBoxes, path;

numBoxes = 0;

$("#new-box").click(function() {
  var defaultContent;
  defaultContent = "<div class='draggable ui-widget-content module_list' id='box-" + numBoxes + "'> I am a new Box!<br><br> Go and add some modules.<br><br> <a class='' href='#'><span class='glyphicon glyphicon-plus'></span></a> </div>";
  $("#boxes").append(defaultContent);
  $("#box-" + numBoxes).draggable({
    snap: true
  }).resizable();
  sidemenu.close();
  numBoxes++;
  $(".module_list").click(function() {
    list("#" + ($(this).attr('id')));
  });
});


/* Show all modules */

path = "./modules";

modules = [];

fs = require("fs");

fs.readdir(path, function(err, files) {
  if (err) {
    throw err;
  }
  modules = files;
});

list = function(boxid) {
  var content, module, _i, _len;
  content = "<ul>";
  for (_i = 0, _len = modules.length; _i < _len; _i++) {
    module = modules[_i];
    content += "<li><a class='module_single' href='#'>" + module + "</a></li>";
  }
  content += "</ul>";
  $(boxid).html(content);
};
