// Generated by CoffeeScript 1.8.0

/* Require modules */
var baseZIndex, configDialogue, data, fs, getNextNum, gui, home_path, list, load_conf, load_module, loaded_modules, modpath, modules, path, session, win,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

fs = require("fs");

gui = require("nw.gui");

path = require("path");


/* Core Logic Preparations */

home_path = process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;

if (!fs.existsSync(home_path + '/.trickle')) {
  fs.mkdirSync(home_path + '/.trickle');
}

if (!fs.existsSync(home_path + '/.trickle/session.json')) {
  fs.writeFileSync(home_path + '/.trickle/session.json', '{ }');
}

try {
  data = fs.readFileSync(home_path + '/.trickle/session.json', "utf8");
  session = JSON.parse(data);
} catch (_error) {
  console.log("gotcha buddy");
  session = {};
}


/* Boxes Logic */

baseZIndex = 50;

configDialogue = "#config-dialogue";

loaded_modules = {};

global.loaded_modules = loaded_modules;

if (!session.present_boxes) {
  session.present_boxes = [];
}

getNextNum = function() {
  var num;
  num = 0;
  while (__indexOf.call(session.present_boxes, num) >= 0) {
    num++;
  }
  return num;
};

$("#new-box").click(function() {
  var defaultContent, numBoxes;
  numBoxes = getNextNum();
  defaultContent = "<div class='draggable ui-widget-content box box-modules' id='box-" + numBoxes + "' style='z-index: " + (baseZIndex + numBoxes) + "'>\n    <div class='box-control'>\n        <span class='glyphicon glyphicon-cog box-control-button'></span>\n    </div>\n    <div class='box-content' id='box-content-" + numBoxes + "'>\n        I am a new Box!<br><br>\n        Go and add some modules.<br><br>\n        <a id='a-" + numBoxes + "' href='#' box-id='" + numBoxes + "'><span class='glyphicon glyphicon-plus'></span></a>\n    </div>\n</div>";
  $("#boxes").append(defaultContent);
  $("#box-" + numBoxes).draggable({
    grid: [10, 10]
  }).resizable({
    grid: 10
  }).center();
  list("#box-content-" + numBoxes, "#box-" + numBoxes);
  $("div#box-content-" + numBoxes + " a#a-" + numBoxes).click(function() {
    return list("#box-content-" + $(this).attr("box-id"));
  });
  return session.present_boxes.push(numBoxes);
});

modpath = "./modules";

modules = [];

fs.readdir(modpath, function(err, files) {
  if (err) {
    throw err;
  }
  return modules = files;
});

list = function(boxid, outer_id) {
  var bcolor, config, content, icon, module, name, _i, _len;
  content = "<h3 style='padding-bottom: 1em;'>Choose your module</h3>";
  content += "<ul>";
  for (_i = 0, _len = modules.length; _i < _len; _i++) {
    module = modules[_i];
    if ((module.charAt(0)) !== '.') {
      config = load_conf(path.join(modpath, module));
      content += "<li class='module-entry'><a class='module-single' href='#' name='" + module + "'";
      if (config) {
        name = config.name;
        bcolor = config.color;
        icon = path.join(modpath, module, config.icon);
      }
      if (bcolor !== "" && bcolor) {
        content += " style='background-color: " + bcolor + ";'";
      }
      content += ">";
      if (icon) {
        content += "<img class='icon' src='" + icon + "' alt='" + module + "'> ";
      }
      if (name !== "" && name) {
        content += "" + name + "</a></li>";
      } else {
        content += "" + module + "</a></li>";
      }
    }
  }
  content += "</ul>";
  $(configDialogue).lightbox_me().html(content);
  return $(".module-single").click(function() {
    return load_module($(this).attr("name"), boxid, outer_id);
  });
};

load_module = function(modname, boxid, outer_id) {
  var config, mod, moddir;
  moddir = path.join(modpath, modname);
  config = load_conf(moddir);
  if (!loaded_modules[outer_id]) {
    loaded_modules[outer_id] = [];
  }
  loaded_modules[outer_id].push(modname);
  if (config) {
    mod = require("./" + path.join(moddir, path.basename(config.hook, path.extname(config.hook))));
    return mod(boxid, configDialogue, session);
  }
};

load_conf = function(moddir) {
  var config, e;
  try {
    config = fs.readFileSync(path.join(moddir, "config.json"), "utf8");
  } catch (_error) {
    e = _error;
    config = null;
  }
  return JSON.parse(config);
};

$.fn.center = function() {
  this.css("position", "absolute");
  this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) + $(window).scrollTop()) + "px");
  this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) + $(window).scrollLeft()) + "px");
  return this;
};


/* Core Logic (Startup and Close) */

win = gui.Window.get();

win.on("close", function() {
  var jsonified;
  this.hide();
  if (!session.boxes) {
    session["boxes"] = {};
  }
  $(".box-modules").each(function(index) {
    var id;
    id = '#' + this.id;
    if (!session.boxes["" + id]) {
      session.boxes["" + id] = {};
    }
    session.boxes["" + id].position = $(id).offset();
    session.boxes["" + id].content = $(id).html();
    session.boxes["" + id].size = {
      "height": $(id).height(),
      "width": $(id).width()
    };
    if (loaded_modules[id]) {
      return session.boxes[id].loaded_modules = loaded_modules[id];
    }
  });
  jsonified = JSON.stringify(root.session, null, 4);
  fs.writeFileSync(home_path + '/.trickle/session.json', jsonified, 'utf8');
  return gui.App.quit();
});
