// Generated by CoffeeScript 1.8.0

/*
    Trickle Core
 */
var fs, gui, root, win;

root = typeof exports !== "undefined" && exports !== null ? exports : this;


/* Require modules */

fs = require("fs");


/* Global variables */

root.session = {};

gui = require("nw.gui");

win = gui.Window.get();

fs.readFile('data/session.json', "utf8", function(err, data) {
  if (err) {
    return console.error(err);
  } else {
    return root.session = JSON.parse(data);
  }
});

win.on("close", function() {
  this.hide();
  return fs.writeFile("data/session.json", JSON.stringify(root.session), function(err) {
    if (err) {
      throw err;
    }
    return gui.App.quit();
  });
});
