// Generated by CoffeeScript 1.8.0
$(function() {
  $(".draggable").draggable({
    snap: true
  });
  $("#box-facebook-trigger").click(function() {
    return $("#box-facebook").show();
  });
  $("#box-twitter-trigger").click(function() {
    return $("#box-twitter").show();
  });
  $("#box-googleplus-trigger").click(function() {
    return $("#box-googleplus").show();
  });
});
