// Generated by CoffeeScript 1.8.0
var dir, modules, path;

modules = typeof exports !== "undefined" && exports !== null ? exports : this;

modules.list = function() {
  console.log("To be implemented...");
};

dir = require("node-dir");

path = "modules";

dir.subdirs(path, function(err, subdirs) {
  console.log(subdirs);
});
