// Generated by CoffeeScript 1.8.0
var list, modules;

modules = typeof exports !== "undefined" && exports !== null ? exports : this;

list = function() {
  console.log("To be implemented");
};

$(function() {
  var dir, path;
  dir = require("node-dir");
  path = "temp_modules";
  modules = [];
  dir.subdirs(path, function(err, subdirs) {
    console.log(subdirs);
  });
});
