// Generated by CoffeeScript 1.8.0
var close, open, sidemenu, toggle;

sidemenu = typeof exports !== "undefined" && exports !== null ? exports : this;

toggle = function() {
  var slideoutMenu, slideoutMenuWidth;
  event.preventDefault();
  slideoutMenu = $(".slideout-menu");
  slideoutMenuWidth = $(".slideout-menu").width();
  slideoutMenu.toggleClass("open");
  if (slideoutMenu.hasClass("open")) {
    slideoutMenu.animate({
      left: "0px"
    });
  } else {
    slideoutMenu.animate({
      left: -slideoutMenuWidth
    }, 200);
  }
};

close = function() {
  var slideoutMenu, slideoutMenuWidth;
  event.preventDefault();
  slideoutMenu = $(".slideout-menu");
  slideoutMenuWidth = $(".slideout-menu").width();
  slideoutMenu.removeClass("open");
  slideoutMenu.animate({
    left: -slideoutMenuWidth
  }, 200);
};

open = function() {
  var slideoutMenu, slideoutMenuWidth;
  event.preventDefault();
  slideoutMenu = $(".slideout-menu");
  slideoutMenuWidth = $(".slideout-menu").width();
  slideoutMenu.addClass("open");
  slideoutMenu.animate({
    left: "0px"
  });
};

$(function() {
  $(".slideout-menu-toggle").click(function(event) {
    toggle();
  });
});
