// Generated by CoffeeScript 1.8.0
$(function() {
  $(".slideout-menu-toggle").click(function(event) {
    var slideoutMenu, slideoutMenuWidth;
    event.preventDefault();
    slideoutMenu = $(".slideout-menu");
    slideoutMenuWidth = $(".slideout-menu").width();
    slideoutMenu.toggleClass("open");
    if (slideoutMenu.hasClass("open")) {
      slideoutMenu.animate({
        left: "0px"
      });
    } else {
      slideoutMenu.animate({
        left: -slideoutMenuWidth
      }, 200);
    }
  });
});
